basepath = "."

locales = [
  "de",
  "es",
  "fr",
  "it",
  "ja",
  "ko",
  "zh-CN",
  "zh-TW",
]

[[includes]]
    path = "mozilla-mobile/android-components/l10n.toml"
[[includes]]
    path = "mozilla-mobile/fenix/l10n.toml"
