
basepath = "."

locales = [
"de",
"es",
"fr",
"it",
"ja",
"ko",
"zh-CN",
"zh-TW",
]

[env]

[[paths]]
  reference = "app/src/main/res/values/strings.xml"
  l10n = "app/src/main/res/values-{android_locale}/strings.xml"
